"""add tables

Revision ID: 97888d411e87
Revises: 2e3697ab41c4
Create Date: 2023-04-27 16:52:40.721760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97888d411e87'
down_revision = '2e3697ab41c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
